config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bands do
    resources :titles
    resources :setlists
  end
  

  #get 'bands/info'
  
  root 'bands#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord

  has_many :titles
  has_many :setlists
  has_many :members
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :band
  
end

app/models/setlist.rb
class Setlist < ApplicationRecord
  belongs_to :band
  has_many :settitels
  has_many :titles, through: :settitels


end

app/models/settitel.rb
class Settitel < ApplicationRecord
  belongs_to :title
  belongs_to :setlist
  
end

app/models/title.rb
class Title < ApplicationRecord
  belongs_to :band
  has_many :settitels
  has_many :setlists, :through => :settitels


  def dauer
    self.duration
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :titlelist]

  def index
    @bands = Band.all.order("id") 
  end

  def show
  end

  def titlelist
  end


  private
  def set_band
    @band = Band.find(params[:id])
  end
  
  def band_params
    params.require(:band).permit(:bandname)
  end 




end

app/controllers/setlists_controller.rb
class SetlistsController < ApplicationController
before_action :set_band 

  def index
    @setlists= @band.setlists.order("setdate desc")
  end

  def show
    @setlist = @band.setlists.find(params[:id])
    @titles = @band.titles 
    @settitel_ids = @setlist.settitels.pluck(:title_id)
    @settitels = @setlist.settitels.order("round", "number")
  end

  private 

  def set_band 
    @band =  Band.find(params[:band_id])
  end

end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  before_action :set_band 


  def index
    @titles=@band.titles 
  end


  private 

  def set_band 
    @band =  Band.find(params[:band_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def dauer_format(dauer)
    #Dauer im Zeitformat anzeigen
    dauer.strftime("%H:%M:%S")
  end

  def dauer_sformat(dauer)
    #Dauer im Zeitformat anzeigen
    dauer.strftime("%M:%S")
  end 

  def kdate(datum)
    #Zeit im Format tt.mm.jj anzeigen
    if (datum == NIL)
      "ohne Datum"
    else
      datum.strftime("%d.%m.%y")
    end
  end

  def mdate(datum)
    #Zeit im Format tt.mm.jj anzeigen
    if (datum == NIL)
      "ohne Datum"
    else
      datum.strftime("%d.%m.%Y")
    end
  end


  def nil_to_string(wert)
    #Wert zurückgeben und wenn nil dann leerer String
    if (wert == NIL)
      retval=""
    else
      retval=wert.to_s
    end
  end

end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/bands/index.html.erb
<h1>Bandliste</h1>
<hr>
<% @bands.each do |band| %>
    <h2><%= link_to band.bandname, band_setlists_path(band)%></h2>
<% end %>

app/views/bands/show.html.erb
<h1>Band: <%= @band.bandname %></h1>
<hr>
<%= @band.members.count %>
 Mitglieder 

<%= @band.titles.count %>
<%= link_to 'Songs', band_titles_path(@band) %>

<%= @band.setlists.count %>
<%= link_to 'Setlisten', band_setlists_path(@band) %>
<%#band_id: @band.id%>
<hr>

app/views/bands/titlelist.html.erb
<h1>Band: <%= @bands.bandname %></h1>
<hr>
<% @bands.titles.each do |t|%>
  <%= t.name %>

  <% end%>%
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mytest3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/setlists/index.html.erb
<div class="container">
  <p><b>Setlisten von <%=@band.bandname %></b>  
  <%= link_to '<Titelliste bearbeiten>', band_titles_path(@band) %>
  (
  <%= @band.titles.count %>
  ) Songs 
  </p>
  <table class="table-sm table-hover table-bordered">  
    <tr>
      <th class="col-sm-3">Name</th>
      <th class="col-sm-3">Datum</th>
      <th class="col-sm-3">Ort</th>
      <th class="col-sm-3">Anzahl Songs</th>
    </tr>
    <% @setlists.each do |setlist| %>
      <%#= link_to band_setlist_path(@band, setlist) do %>
        <tr>
        <!--<div style="margin: 5px; padding: 5px; border: 1px solid black;"> 
          <% if setlist.setname.nil? %>
            ohne Namen -
          <% else %>
            <%= setlist.setname %>
          <% end %>
          am 
          <%= kdate(setlist.setdate)%>
          (
          <%= setlist.settitels.count%>
           Songs)
        </div> -->
          <td class="col-sm-3"><%= link_to setlist.setname, band_setlist_path(@band, setlist) %></td>
          <td class="col-sm-3"><%= mdate(setlist.setdate)%></td>
          <td class="col-sm-3"><%= setlist.setlocation%>
          <td class="col-sm-3"><%= setlist.settitels.count%></td>   
        </tr>
      <%# end %>
    <% end %>
  </table>
</div>

app/views/setlists/show.html copy 2.erb
<h1><%= @setlist.setname %></h1>
<hr>
<% myround=0%>
<% @settitels.each do |title| %>
  <div clas="container">
    <div class="table">
      <tr>
      <% if !(myround == title.round)  %>
          <div class="col-sm-12", >Runde 
            <%= myround = title.round %> Anzahl der Titel:
            <%= @settitels.where("round = ?", myround).count%>
          </div>
      <% end %>
      <div class="col-sm-1"><%= title.number%></div>
      <div class="col-sm-2"><%= title.title.titel%></div>
      <div class="col-sm-1"><%= title.title.bpm%></div>
      <div class="col-sm-1"><%= dauer_sformat(title.title.duration)%></div>
      </tr>
    </div>
  </div>
  
<% end %>

app/views/setlists/show.html copy 3.erb
<h1><%= @setlist.setname %></h1>
<hr>
<% myround=0%>
<% @settitels.each do |title| %>
  <div class="container">
    
      
          <% if !(myround == title.round)  %>
              <div class="col-12", >Runde 
              <%= myround = title.round %>
              (<%= @settitels.where("round = ?", myround).count%> Titel)
              </div>
            <% end %>
          <div class="col-sm-1"><%= title.number%></div>
          <div class="col-sm-3"><%= title.title.titel%></div>
          <div class="col-sm-1"><%= title.title.bpm%></div>
          <div class="col-sm-1"><%= dauer_sformat(title.title.duration)%></div>
       
    
  </div>
  
<% end %>

app/views/setlists/show.html copy.erb
<br>
<h1><%= @setlist.setname %></h1>

<hr>
<%= @titles.count %>
<hr>
<% @titles.each do |title| %>
  
    <% if !@settitel_ids.include?(title.id) %>
      <div>
        <%= title.titel %>
      </div>
    <% else %>
      <div style="margin: 5px; padding: 5px; background: green;">%>
        <%= title.titel %>
      </div>
  
  <% end %>
<% end %>

app/views/setlists/show.html.erb
<div class="container">
  <p><b><%= @setlist.setname + " am " +  mdate(@setlist.setdate).to_s + " in " + nil_to_string(@setlist.setlocation)%></b></p>
  <% myround=0%>
  <% @settitels.each do |title| %>
  
    
      <table class="table-sm table-hover table-bordered">
          <% if !(myround == title.round)  %>
            <tr style="color: white; background: green">
              <th colspan="4" class="col-sm-12">Runde 
              <%= myround = title.round %>
              (<%= @settitels.where("round = ?", myround).count%> Titel) Dauer: ##.##.##
              <%#= @settitels.where("round = ?", myround).sum(:title.dauer)%>
              </th>
            </tr>
          <% end %>
        <tr>
          <td class="col-sm-2"><%= title.number%></td>
          <td class="col-sm-6"><%= title.title.titel.truncate(25)%></td>
          <td class="col-sm-2"><%= title.title.bpm%></td>
          <td class="col-sm-2"><%= dauer_sformat(title.title.duration)%></td>
        </tr>
      </table>
    
  <% end %>
</div>

app/views/titles/index.html.erb
<h1>Titelliste <%=@band.bandname %></h1>
<hr>
<% @titles.each do |t| %>
  <%= link_to edit_band_title_path(@band, t) do %>
<!--    <div style="margin: 5px; padding: 5px; border: 1px solid black;"> -->
    <div class="row">
      <div class="col-md-1"><%=t.id%></div>
      <div class="col-md-3"><%= t.titel %></div>
      <div class="col-md-3"><%= t.interpret %></div>
      <div class="col-md-1"><%= t.bpm %></div>
      <div class="col-md-2"><%= dauer_format(t.duration) %></div>  
      <div class="col-md-2"><%= 1000 * dauer_format(t.duration).to_f %></div>  
    </div>
  <% end %>
<% end %>